version: '2'
volumes:
    meantemplatemongodata:
    meantemplatenodemodules:
services:
    mean-template-nodejs:
        build: .
        image: "mean-template-nodejs"
        container_name: "mean-template-nodejs"
        environment:
            - NODE_ENV=development
        volumes:
            - .:/app/meantemplate/:rw
            - ./data/root:/root/:rw
            - meantemplatenodemodules:/app/meantemplate/node_modules/
        ports:
            - 8080:8080
            - 9000:9000
            - 9001:9001
        networks:
            mean-template:
                aliases:
                    - mean-template-nodejs
        depends_on:
            - mean-template-mongodb
            - mean-template-selenium-chrome
            - mean-template-selenium-firefox
    # https://hub.docker.com/_/mongo
    mean-template-mongodb:
        image: mongo:4
        container_name: "mean-template-mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - meantemplatemongodata:/data/db
        ports:
            - 27017:27017
        command: mongod --bind_ip 0.0.0.0
        networks:
            mean-template:
                aliases:
                    - mean-template-mongodb
    # https://github.com/SeleniumHQ/docker-selenium/releases
    mean-template-selenium-chrome:
        image: selenium/standalone-chrome:3.141.59-zinc
        container_name: "mean-template-selenium-chrome"
        ports:
            - 4444:4444
        networks:
            mean-template:
                aliases:
                    - mean-template-selenium-chrome

    # https://github.com/SeleniumHQ/docker-selenium/releases
    mean-template-selenium-firefox:
        image: selenium/standalone-firefox:3.141.59
        container_name: "mean-template-selenium-firefox"
        ports:
            - 4445:4444
        networks:
            mean-template:
                aliases:
                    - mean-template-selenium-firefox
networks:
    mean-template:
